### ISSUE TITLE
SciTail not using SAN

### ISSUE THREAD

**Issue by ZhaofengWu** [namisan/mt-dnn#11]
Looks like by default SciTail does not use SAN, because it uses the default value for `--answer_opt`, which is 0. Why is that?

**Comment by namisan** [comment]
The purpose is to test generalization of the learned embedding instead of complicated model structures for a direct comparison with _BERT_. Thus, we use answer_opt=0 on the **domain adaptation setting**.  However, you will observe some improvement if you use _SAN_ here, e.g., we was able to get 96.x on dev in our experiment.

**Comment by ZhaofengWu** [comment]
So you are saying, only by changing the default value for `--answer_opt` from 0 to 1, I should see better performance when running the `scitail_domain_adaptation_bash.sh`?

**Comment by namisan** [comment]
It should be, at least in our experiments.

**Comment by ZhaofengWu** [comment]
Thanks!
