### ISSUE TITLE
How to reproduce the result on QNLI?

### ISSUE THREAD

**Issue by zdou0830** [namisan/mt-dnn#8]
Hi, I am having trouble reproducing the result on the QNLI dataset. How did you choose the hyper-parameters?

**Comment by namisan** [comment]
The result on QNLI reported in our paper was on the GLUE old version (please refer GLUE official homepage for more details). As in the paper, we treat QNLI as a ranking task instead of a classification task, which gave a great improvement. However, this is not a case in the current version. If you are able to find old QNLI datasets, you should be able get the results as reported in the paper, e.g., use _qnnli_ tasks as our codes.
